<?php declare(strict_types=1);

namespace Builder\Social\Model\Resource;

use Framework\Database\Abstract\Resource\Model as AbstractResourceModel;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-08-31 16:20:52
 *
 * @class Builder\Social\Model\Resource\Social
 * @package Builder\Social\Model\Resource
 */
class Social extends AbstractResourceModel 
{
    /**
     * @throws Exception
     */
    public function __construct()
    {
        parent::__construct('social');
    }
}
