<?php declare(strict_types=1);

namespace Builder\Page\Model;

use Framework\Database\Abstract\Model as AbstractModel;

/**
 * Generated by www.Tereta.dev on 2024-08-25 18:18:15
 *
 * @class Builder\Page\Model\Type
 * @package Builder\Page\Model
 */
class Type extends AbstractModel 
{
}
