<?php declare(strict_types=1);

namespace Builder\Page\Model;

use Framework\Database\Abstract\Model as AbstractModel;

/**
 * Generated by www.Tereta.dev on 2024-08-25 18:38:05
 *
 * @class Builder\Page\Model\Url
 * @package Builder\Page\Model
 */
class Url extends AbstractModel 
{
}
