<?php declare(strict_types=1);

namespace Builder\Theme\Model\Resource;

use Framework\Database\Abstract\Resource\Model as AbstractResourceModel;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-09-08 05:18:40
 *
 * @class Builder\Theme\Model\Resource\Theme
 * @package Builder\Theme\Model\Resource
 */
class Theme extends AbstractResourceModel 
{
    /**
     * @throws Exception
     */
    public function __construct()
    {
        parent::__construct('theme');
    }
}
