<?php declare(strict_types=1);

namespace Builder\Social\Model\Resource\Social;

use Framework\Database\Abstract\Resource\Collection as AbstractCollectionModel;
use Builder\Social\Model\Resource\Social as ResourceModel;
use Builder\Social\Model\Social as Model;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-08-31 16:20:52
 *
 * @class Builder\Social\Model\Resource\Social\Collection
 * @package Builder\Social\Model\Resource\Social
 */
class Collection extends AbstractCollectionModel 
{
    /**
     * @throws Exception
     */
    public function __construct()
    {
        parent::__construct(ResourceModel::class, Model::class);
    }
}
