<?php declare(strict_types=1);

namespace Builder\Site\Cli;

use Framework\Cli\Interface\Controller;
use Framework\Cli\Symbol;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-09-13 20:13:15
 *
 * @class Builder\Site\Cli\Manager
 * @package Builder\Site\Cli
 */
class Manager implements Controller
{
    /**
     * @cli site:manager:create
     * @cliDescription Create new site
     * @param string $identifier identifier of the site
     * @return void
     * @throws Exception
     */
    public function create(string $identifier): void
    {
        echo Symbol::COLOR_GREEN . "The sample script successfully performed\n" . Symbol::COLOR_RESET;
    }
}