<?php declare(strict_types=1);

namespace Builder\Page\Model\Resource;

use Framework\Database\Abstract\Resource\Model as AbstractResourceModel;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-08-25 18:18:37
 *
 * @class Builder\Page\Model\Resource\Type
 * @package Builder\Page\Model\Resource
 */
class Type extends AbstractResourceModel 
{
    /**
     * @throws Exception
     */
    public function __construct()
    {
        parent::__construct('pageType');
    }
}
