<?php declare(strict_types=1);

namespace Builder\Content\Cli;

use Builder\Site\Model\Resource\Site as SiteResourceModel;
use Builder\Site\Model\Site as SiteModel;
use Framework\Cli\Interface\Controller;
use Framework\Cli\Symbol;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-08-25 17:46:22
 *
 * @class Builder\Content\Cli\Make
 * @package Builder\Content\Cli
 */
class Make implements Controller
{
    /**
     * @cli make:sample:content
     * @cliDescription Sample CLI command
     * @return void
     * @throws Exception
     */
    public function make(): void
    {
        // Make a new site
        $siteResourceModel = (new SiteResourceModel);
        $siteResourceModel->load($siteModel = new SiteModel(), 'sample', 'identifier');

        $siteId = $siteModel->get('id');
        if (!$siteId) {
            throw new Exception("The \"sample\" site not found");
        }
        echo Symbol::COLOR_GREEN . "The \"{$siteModel->get('identifier')}\" [{$siteId}] site will be used for the sample content page\n" . Symbol::COLOR_RESET;


    }
}