<?php declare(strict_types=1);

namespace Builder\Content\Cli;

use Builder\Site\Model\Repository as SiteRepository;
use Framework\Cli\Interface\Controller;
use Framework\Cli\Symbol;
use Exception;
use Builder\Content\Model\Resource\Content as ContentResourceModel;
use Builder\Content\Model\Content as ContentModel;
use Builder\Page\Model\Type\Repository as PageTypeRepository;
use Builder\Page\Model\Url as UrlModel;
use Builder\Page\Model\Resource\Url as UrlResourceModel;

/**
 * Generated by www.Tereta.dev on 2024-08-25 17:46:22
 *
 * @class Builder\Content\Cli\Make
 * @package Builder\Content\Cli
 */
class Make implements Controller
{
    /**
     * @cli make:sample:content
     * @cliDescription Sample CLI command
     * @return void
     * @throws Exception
     */
    public function make(): void
    {
        // Make a new site
        $siteModel = SiteRepository::getInstance()->getByIdentifier('sample');

        $siteId = $siteModel->get('id');
        if (!$siteId) {
            throw new Exception("The \"sample\" site not found");
        }
        echo Symbol::COLOR_GREEN . "The \"{$siteModel->get('identifier')}\" [{$siteId}] site will be used for the sample content page\n" . Symbol::COLOR_RESET;

        // Make a new content page
        $contentModel = new ContentModel([
            'siteId' => $siteId,
            'identifier' => 'home',
            'seoUri' => '/',
            'seoTitle' => 'Sample Home Page',
            'title' => 'Sample Home Page',
            'content' => 'This is a sample home content page',
            'status' => 1,
        ]);

        $contentResourceModel = (new ContentResourceModel);
        $contentResourceModel->save($contentModel);
        $contentResourceModel->load($contentModel, ['siteId' => $siteId, 'identifier' => 'home']);

        echo Symbol::COLOR_GREEN . "The \"{$contentModel->get('identifier')}\" [{$contentModel->get('id')}] page has been created.\n" . Symbol::COLOR_RESET;

        // Make a url rewrite
        $typeModel = PageTypeRepository::getInstance()->getType('content');
        $urlResourceModel = new UrlResourceModel;
        $urlModel = new UrlModel([
            'siteId'     => $siteId,
            'typeId'     => $typeModel->get('id'),
            'identifier' => $contentModel->get('id'),
            'uri'        => '/',
        ]);
        $urlResourceModel->save($urlModel);
        $urlResourceModel->load($urlModel, ['siteId' => $siteId, 'uri' => '/']);
        $schema = $siteModel->getDomainModel()->get('secure') ? 'https' : 'http';
        echo Symbol::COLOR_GREEN . "The \"{$schema}://{$siteModel->getDomainModel()->get('domain')}{$urlModel->get('uri')}\" [{$urlModel->get('id')}] sute url has been created.\n" . Symbol::COLOR_RESET;
    }
}