<?php declare(strict_types=1);

namespace Builder\Page\Api;

use Framework\Api\Interface\Api as Api;
use Exception;
use Framework\Application\Manager\Http\Parameter\Post as PostData;

/**
 * Generated by www.Tereta.dev on 2024-09-01 17:55:49
 *
 * @class Builder\Page\Api\Files
 * @package Builder\Page\Api
 */
class Files implements Api 
{
    /**
     * @param PostData $postData
     * @return array
     * @api POST /^files\/getDirectory/Usi
     */
    public function getDirectory(PostData $postData): array
    {
        return [
            'pathDir' => $postData->get('pathDir'),
            'listing' => [],
            'error' => null
        ];
    }

    /**
     * @param PostData $postData
     * @return array
     * @api POST /^files\/createFolder/Usi
     */
    public function createFolder(PostData $postData): array
    {
        $pathDirectory = $postData->get('path');

        return [
            'pathDir' => $postData->get('pathDir'),
            'listing' => [],
            'error' => null
        ];
    }

    /**
     * @param PostData $postData
     * @return array
     * @api POST /^files\/uploadFile/Usi
     */
    public function uploadFile(PostData $postData): array
    {
        $filePath = $postData->get('path');
        $pathDir = $postData->get('pathDir');
        $file = $_FILES['file'] ?? null;

        return [
            'pathDir' => $postData->get('pathDir'),
            'listing' => [],
            'error' => null
        ];
    }
}
