<?php declare(strict_types=1);

namespace Builder\Page\Api;

use Framework\Api\Interface\Api as Api;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-09-01 17:55:49
 *
 * @class Builder\Page\Api\Files
 * @package Builder\Page\Api
 */
class Files implements Api 
{
    /**
     * @return array
     * @throws Exception
     * @api POST /^files\/getDirectory/Usi
     */
    public function getDirectory(): array
    {
        return [
            'pathDir' => '/path/to/directory',
            'listing' => [],
            'error' => null
        ];
    }
}
