<?php declare(strict_types=1);

namespace Builder\Site\Model\Resource;

use Framework\Database\Abstract\Resource\Model as AbstractResourceModel;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-10-10 20:19:58
 *
 * @class Builder\Site\Model\Resource\Style
 * @package Builder\Site\Model\Resource
 */
class Style extends AbstractResourceModel 
{
    /**
     * @throws Exception
     */
    public function __construct()
    {
        parent::__construct('siteStyle');
    }
}
