<?php declare(strict_types=1);

namespace Builder\Content\Model\Resource\Url;

use Framework\Database\Abstract\Resource\Collection as AbstractCollectionModel;
use Builder\Content\Model\Resource\Url as ResourceModel;
use Builder\Content\Model\Url as Model;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-08-25 18:32:41
 *
 * @class Builder\Content\Model\Resource\Url\Collection
 * @package Builder\Content\Model\Resource\Url
 */
class Collection extends AbstractCollectionModel 
{
    /**
     * @throws Exception
     */
    public function __construct()
    {
        parent::__construct(ResourceModel::class, Model::class);
    }
}
