<?php declare(strict_types=1);

namespace Builder\Site\Model\Site\Configuration;

use Framework\Database\Abstract\Model as AbstractModel;

/**
 * Generated by www.Tereta.dev on 2024-09-08 12:41:26
 *
 * @class Builder\Site\Model\Site\Configuration\Value
 * @package Builder\Site\Model\Site\Configuration
 */
class Value extends AbstractModel 
{
}
