<?php declare(strict_types=1);

namespace Builder\User\Setup;

use Framework\Application\Setup\Abstract\Upgrade as AbstractUpgrade;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-08-31 16:26:25
 *
 * @class Builder\Social\Setup\Structure
 * @package Builder\Social\Setup
 */
class Structure extends AbstractUpgrade 
{
    /**
     * @date 2024-09-15 16:26:25 addSiteId
     * @return void
     * @throws Exception
     */
    public function addSiteId(){
        $connection = $this->connection;

        $connection->query(
            'ALTER TABLE `user` ADD COLUMN `siteId` int unsigned NOT NULL AFTER `id`'
        );
        $connection->query(
            'ALTER TABLE `user` ADD CONSTRAINT `fk_user_siteId`' .
                ' FOREIGN KEY (`siteId`) REFERENCES `site` (`id`) ON DELETE CASCADE ON UPDATE CASCADE'
        );
    }
}
