<?php declare(strict_types=1);

namespace Builder\Site\Model;

use Framework\Database\Abstract\Model as AbstractModel;

/**
 * Generated by www.Tereta.dev on 2024-10-10 20:19:58
 *
 * @class Builder\Site\Model\Style
 * @package Builder\Site\Model
 */
class Style extends AbstractModel 
{
}
