<?php declare(strict_types=1);

namespace Builder\Site\Model\Resource\Site\Configuration\Value;

use Framework\Database\Abstract\Resource\Collection as AbstractCollectionModel;
use Builder\Site\Model\Resource\Site\Configuration\Value as ResourceModel;
use Builder\Site\Model\Site\Configuration\Value as Model;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-09-08 12:41:26
 *
 * @class Builder\Site\Model\Resource\Site\Configuration\Value\Collection
 * @package Builder\Site\Model\Resource\Site\Configuration\Value
 */
class Collection extends AbstractCollectionModel 
{
    /**
     * @throws Exception
     */
    public function __construct()
    {
        parent::__construct(ResourceModel::class, Model::class);
    }
}
