<?php declare(strict_types=1);

namespace Builder\Content\Model;

use Framework\Database\Abstract\Model as AbstractModel;

/**
 * Generated by www.Tereta.dev on 2024-08-25 13:15:58
 *
 * @class Builder\Content\Model\Content
 * @package Builder\Content\Model
 */
class Content extends AbstractModel 
{
}
