<?php declare(strict_types=1);

namespace Builder\Content\Model;

use Framework\Database\Abstract\Model as AbstractModel;

/**
 * Generated by www.Tereta.dev on 2024-08-25 18:32:41
 *
 * @class Builder\Content\Model\Url
 * @package Builder\Content\Model
 */
class Url extends AbstractModel 
{
}
