<?php declare(strict_types=1);

namespace Builder\Social\Model;

use Framework\Database\Abstract\Model as AbstractModel;

/**
 * Generated by www.Tereta.dev on 2024-08-31 16:20:52
 *
 * @class Builder\Social\Model\Social
 * @package Builder\Social\Model
 */
class Social extends AbstractModel 
{
}
