<?php declare(strict_types=1);

namespace Builder\Page\Model\Url;

use Builder\Page\Model\Resource\Url as UrlResource;
use Builder\Page\Model\Type\Repository as UrlTypeRepository;
use Builder\Page\Model\Url as UrlModel;
use Builder\Site\Model\Repository as SiteRepository;
use Framework\Database\Abstract\Repository as AbstractRepository;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-08-29 10:26:16
 *
 * @class Builder\Page\Model\Url\Repository
 * @package Builder\Page\Model\Url
 */
class Repository extends AbstractRepository 
{

    /**
     * @var array $registeredKeys
     */
    protected array $registeredKeys = ['id', ['siteId', 'identifier'], ['siteId', 'uri']];

    /**
     * @param string $host
     * @param string $path
     * @return UrlModel
     * @throws Exception
     */
    public function getByUrl(string $host, string $path): UrlModel
    {
        if ($registeredModel = $this->getRegisterModel(['siteId' => $host, 'uri' => $path])) {
            return $registeredModel;
        }

        $siteModel = SiteRepository::getInstance()->getByDomain($host);

        UrlResource::getInstance()->load($urlModel = new UrlModel, [
            'siteId' => $siteModel->get('id'),
            'uri' => $path,
        ]);

        return $this->setRegisterModel($urlModel);
    }

    public function loadUrl(UrlModel $urlModel): UrlModel
    {
        $typeId = UrlTypeRepository::getInstance()->getTypeByIdentifier($urlModel->get('typeClass'))->get('id');

        UrlResource::getInstance()->load($urlModel, [
            'siteId' => $urlModel->get('siteId'),
            'typeId' => $typeId,
            'identifier' => $urlModel->get('identifier'),
        ]);

        return $this->setRegisterModel($urlModel);
    }

    /**
     * @param UrlModel $urlModel
     * @return UrlModel
     * @throws Exception
     */
    public function saveUrl(UrlModel $urlModel): UrlModel
    {
        if (!is_int($urlModel->get('typeId'))) {
            $typeId = UrlTypeRepository::getInstance()->getType($urlModel->get('typeId'))->get('id');
            $urlModel->set('typeId', $typeId);
        }

        UrlResource::getInstance()->load($loadUrl = new UrlModel, [
            'siteId' => $urlModel->get('siteId'),
            'typeId' => $urlModel->get('typeId'),
            'identifier' => $urlModel->get('identifier'),
        ]);

        if ($loadUrl->get('id')) {
            $urlModel->set('id', $loadUrl->get('id'));
        }

        UrlResource::getInstance()->save($urlModel);

        return $this->setRegisterModel($urlModel);
    }
}
