<?php declare(strict_types=1);

namespace Builder\Page\Model\Url;

use Builder\Page\Model\Resource\Url as UrlResource;
use Builder\Page\Model\Type\Repository as UrlTypeRepository;
use Builder\Page\Model\Url as UrlModel;
use Framework\Database\Abstract\Repository as AbstractRepository;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-08-29 10:26:16
 *
 * @class Builder\Page\Model\Url\Repository
 * @package Builder\Page\Model\Url
 */
class Repository extends AbstractRepository 
{
    /**
     * @var array $registeredKeys
     */
    protected array $registeredKeys = ['id', ['siteId', 'identifier'], ['siteId', 'uri']];

    /**
     * @param UrlModel $urlModel
     * @return UrlModel
     * @throws Exception
     */
    public function saveUrl(UrlModel $urlModel): UrlModel
    {
        if (!is_int($urlModel->get('typeId'))) {
            $typeId = UrlTypeRepository::getInstance()->getType($urlModel->get('typeId'))->get('id');
            $urlModel->set('typeId', $typeId);
        }

        UrlResource::getInstance()->load($loadUrl = new UrlModel, [
            'siteId' => $urlModel->get('siteId'),
            'typeId' => $urlModel->get('typeId'),
            'identifier' => $urlModel->get('identifier'),
        ]);

        if ($loadUrl->get('id')) {
            $urlModel->set('id', $loadUrl->get('id'));
        }

        UrlResource::getInstance()->save($urlModel);

        return $this->setRegisterModel($urlModel);
    }
}
