<?php declare(strict_types=1);

namespace Builder\Theme\Model;

use Framework\Database\Abstract\Model as AbstractModel;

/**
 * Generated by www.Tereta.dev on 2024-09-08 05:18:40
 *
 * @class Builder\Theme\Model\Theme
 * @package Builder\Theme\Model
 */
class Theme extends AbstractModel 
{
}
