<?php declare(strict_types=1);

namespace Builder\Site\Model\Resource\Site;

use Builder\Site\Model\Site\Configuration as ModelConfiguration;
use Framework\Database\Abstract\Resource\Model as AbstractResourceModel;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-09-08 12:35:53
 *
 * @class Builder\Site\Model\Resource\Site\Configuration
 * @package Builder\Site\Model\Resource\Site
 */
class Configuration extends AbstractResourceModel 
{
    /**
     * @throws Exception
     */
    public function __construct()
    {
        parent::__construct('siteConfiguration');
    }

    public function loadByPath(ModelConfiguration $model, int $siteId, string $path): void
    {
        $this->getSelect()->leftJoin(
            ['scv' => 'siteConfigurationValue'],
            'scv.pathId = main.id AND scv.siteId = ' . $siteId
        )->columns(['main.id' => 'pathId'], ['scv.id' => 'id'], 'path', 'value', 'siteId');
        $this->load($model, ['path' => $path]);
    }
}
