<?php declare(strict_types=1);

namespace Builder\Social\Setup;

use Framework\Application\Setup\Abstract\Upgrade as AbstractUpgrade;
use Framework\Database\Factory;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-08-31 16:26:25
 *
 * @class Builder\Social\Setup\Structure
 * @package Builder\Social\Setup
 */
class Structure extends AbstractUpgrade 
{
    /**
     * @date 2024-08-31 16:26:25 Created
     * @return void
     * @throws Exception
     */
    public function create(){
        $connection = $this->connection;

        $query = Factory::createTable('social');
        $query->addForeign($connection, 'siteId')->foreign('site', 'id')->setPrimaryKey()->setComment('Site ID');
        $query->addString('facebook', $query::TYPE_VARCHAR)->setComment('Facebook URL');
        $query->addString('instagram', $query::TYPE_VARCHAR)->setComment('Instagram URL');
        $query->addString('pinterest', $query::TYPE_VARCHAR)->setComment('Pinterest URL');
        $query->addString('linkedin', $query::TYPE_VARCHAR)->setComment('Linkedin URL');
        $query->addString('youtube', $query::TYPE_VARCHAR)->setComment('Youtube URL');
        $connection->query($query->build());
    }
}
