<?php declare(strict_types=1);

namespace Builder\Site\Model\Resource\Style;

use Framework\Database\Abstract\Resource\Collection as AbstractCollectionModel;
use Builder\Site\Model\Resource\Style as ResourceModel;
use Builder\Site\Model\Style as Model;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-10-10 20:19:58
 *
 * @class Builder\Site\Model\Resource\Style\Collection
 * @package Builder\Site\Model\Resource\Style
 */
class Collection extends AbstractCollectionModel 
{
    /**
     * @throws Exception
     */
    public function __construct()
    {
        parent::__construct(ResourceModel::class, Model::class);
    }
}
