<?php declare(strict_types=1);

namespace Builder\Content\Model\Resource;

use Framework\Database\Abstract\Resource\Model as AbstractResourceModel;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-08-25 13:44:56
 *
 * @class Builder\Content\Model\Resource\Content
 * @package Builder\Content\Model\Resource
 */
class Content extends AbstractResourceModel 
{
    /**
     * @throws Exception
     */
    public function __construct()
    {
        parent::__construct('pageContent');
    }
}
