<?php declare(strict_types=1);

namespace Builder\Content\Model\Resource;

use Framework\Database\Abstract\Resource\Model as AbstractResourceModel;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-08-25 18:32:41
 *
 * @class Builder\Content\Model\Resource\Url
 * @package Builder\Content\Model\Resource
 */
class Url extends AbstractResourceModel 
{
    /**
     * @throws Exception
     */
    public function __construct()
    {
        parent::__construct('pageUrl');
    }
}
