<?php declare(strict_types=1);

namespace Builder\Content\Model\Resource\Content;

use Framework\Database\Abstract\Resource\Collection as AbstractCollectionModel;
use Builder\Content\Model\Resource\Content as ResourceModel;
use Builder\Content\Model\Content as Model;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-08-25 13:44:28
 *
 * @class Builder\Content\Model\Resource\Content\Collection
 * @package Builder\Content\Model\Resource\Content
 */
class Collection extends AbstractCollectionModel 
{
    /**
     * @throws Exception
     */
    public function __construct()
    {
        parent::__construct(ResourceModel::class, Model::class);
    }

    /**
     * @todo Need to move to separated trait!!!
     * @param array $identifiers
     * @return self
     * @throws Exception
     */
    public function filterByIdentifiers(array $identifiers): self
    {
        $identifiers = array_filter($identifiers, 'is_int');
        $this->getSelect()->where('id IN (' . implode(", ",  $identifiers) . ')');

        return $this;
    }
}
