<?php declare(strict_types=1);

namespace Builder\Page\Model\Resource\Type;

use Framework\Database\Abstract\Resource\Collection as AbstractCollectionModel;
use Builder\Page\Model\Type as ResourceModel;
use Builder\Page\Model\Resource\Type as Model;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-08-25 18:21:24
 *
 * @class Builder\Page\Model\Resource\Type\Collection
 * @package Builder\Page\Model\Resource\Type
 */
class Collection extends AbstractCollectionModel 
{
    /**
     * @throws Exception
     */
    public function __construct()
    {
        parent::__construct(ResourceModel::class, Model::class);
    }
}
