<?php declare(strict_types=1);

namespace Builder\Theme\Model\Resource\Theme;

use Framework\Database\Abstract\Resource\Collection as AbstractCollectionModel;
use Builder\Theme\Model\Resource\Theme as ResourceModel;
use Builder\Theme\Model\Theme as Model;
use Exception;

/**
 * Generated by www.Tereta.dev on 2024-09-08 05:18:40
 *
 * @class Builder\Theme\Model\Resource\Theme\Collection
 * @package Builder\Theme\Model\Resource\Theme
 */
class Collection extends AbstractCollectionModel 
{
    /**
     * @throws Exception
     */
    public function __construct()
    {
        parent::__construct(ResourceModel::class, Model::class);
    }
}
