<?php declare(strict_types=1);

namespace Builder\Site\Model\Site;

use Framework\Database\Abstract\Model as AbstractModel;

/**
 * Generated by www.Tereta.dev on 2024-09-08 12:35:53
 *
 * @class Builder\Site\Model\Site\Configuration
 * @package Builder\Site\Model\Site
 */
class Configuration extends AbstractModel 
{
}
